version: '3.8'

services:
  web:
    build: ./punchTheClock
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./punchTheClock:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data_dev: